#!/bin/bash

THEME="$1"
TOML="$HOME/.config/themes/$THEME/colors.toml"

# Load colors from TOML in a single pass (0ms overhead)
declare -A colors
while IFS= read -r line; do
  if [[ "$line" =~ ^[[:space:]]*([a-zA-Z0-9_]+)[[:space:]]*=[[:space:]]*\"([^\"]+)\" ]]; then
    colors["${BASH_REMATCH[1]}"]="${BASH_REMATCH[2]}"
  elif [[ "$line" =~ ^[[:space:]]*([a-zA-Z0-9_]+)[[:space:]]*=[[:space:]]*([0-9.]+) ]]; then
    colors["${BASH_REMATCH[1]}"]="${BASH_REMATCH[2]}"
  fi
done < "$TOML"

background="${colors[background]}"
background2="${colors[background2]}"
foreground="${colors[foreground]}"
foreground2="${colors[foreground2]}"
border="${colors[border]}"
accent="${colors[accent]}"
inactive="${colors[inactive]}"

# Fallbacks
[ -z "$background" ] && background="#F4EFE4"
[ -z "$background2" ] && background2="#EDE7D3"
[ -z "$foreground" ] && foreground="#0D0D0D"
[ -z "$foreground2" ] && foreground2="#3A3A3A"
[ -z "$border" ]     && border="#0D0D0D"
[ -z "$accent" ]     && accent="#D94F2B"
[ -z "$inactive" ]   && inactive="#C8C2B4"

mkdir -p ~/.config/btop/themes

# Write shade-raid.theme
cat > ~/.config/btop/themes/shade-raid.theme << THEME_EOF
# btop theme auto-generated by btop.sh theme generator
# Theme: $THEME

# Main UI elements
theme[main_bg]="$background"
theme[main_fg]="$foreground"
theme[title]="$accent"
theme[hi_fg]="$accent"
theme[selected_bg]="$background2"
theme[selected_fg]="$foreground"
theme[inactive_fg]="$inactive"
theme[graph_text]="$foreground2"

# Box outlines
theme[cpu_box]="$border"
theme[mem_box]="$border"
theme[net_box]="$border"
theme[proc_box]="$border"
theme[div_line]="$border"

# Temp colors
theme[temp_start]="$inactive"
theme[temp_mid]="$accent"
theme[temp_end]="$accent"

# CPU graph / meter
theme[cpu_start]="$inactive"
theme[cpu_mid]="$accent"
theme[cpu_end]="$accent"

# Memory
theme[free_start]="$inactive"
theme[free_mid]="$accent"
theme[free_end]="$accent"
theme[cached_start]="$inactive"
theme[cached_mid]="$accent"
theme[cached_end]="$accent"
theme[available_start]="$inactive"
theme[available_mid]="$accent"
theme[available_end]="$accent"
theme[used_start]="$inactive"
theme[used_mid]="$accent"
theme[used_end]="$accent"

# Download / Upload
theme[download_start]="$inactive"
theme[download_mid]="$accent"
theme[download_end]="$accent"
theme[upload_start]="$inactive"
theme[upload_mid]="$accent"
theme[upload_end]="$accent"

# Process meter
theme[process_start]="$inactive"
theme[process_mid]="$accent"
theme[process_end]="$accent"
THEME_EOF

# Update btop.conf to use this theme
CONF_FILE="$HOME/.config/btop/btop.conf"
if [ -f "$CONF_FILE" ]; then
    sed -i 's/^color_theme[[:space:]]*=.*/color_theme = "shade-raid"/' "$CONF_FILE"
fi

echo "Generated ~/.config/btop/themes/shade-raid.theme and updated btop.conf"
