import json
from pathlib import Path
from dotfiles_api.domain.contracts.action import Action
from dotfiles_api.context.execution import ExecutionContext
from dotfiles_api.context.environment import EnvironmentContext

class DrawerAction(Action):
    def __init__(self, exec_ctx: ExecutionContext, env: EnvironmentContext) -> None:
        self._exec = exec_ctx
        self._env = env

    def execute(self, args: list[str]) -> None:
        res = self._exec.execute(["hyprctl", "monitors", "-j"])
        monitors_data = res.stdout.strip()
        
        px_w = 2560
        px_h = 1440
        scale = 1.0

        if monitors_data:
            try:
                monitors = json.loads(monitors_data)
                if monitors:
                    mon = next((m for m in monitors if m.get("focused")), monitors[0])
                    px_w = mon.get("width", px_w)
                    px_h = mon.get("height", px_h)
                    scale = mon.get("scale", scale)
            except Exception:
                pass

        log_w = int(px_w / scale)
        log_h = int(px_h / scale)
        
        bar_y = 39

        btop_w, btop_h = 1400, 600
        pavu_w, pavu_h = 800, 600
        nm_w, nm_h = 700, 420
        bt_w, bt_h = 700, 520
        editor_w, editor_h = 700, 600

        btop_x = (log_w - btop_w) // 2
        pavu_x = (log_w - pavu_w) // 2
        nm_x = (log_w - nm_w) // 2
        bt_x = (log_w - bt_w) // 2

        editor_x = log_w - editor_w - 10
        editor_y = (log_h - editor_h) // 2

        content = f"""-- Auto-generated by DrawerAction -- do not edit manually
-- Monitor: {px_w}x{px_h} @ scale {scale} -> logical {log_w}px wide

-- Special workspaces (drawers) with auto-start commands
hl.workspace_rule({{ workspace = "special:btop",     on_created_empty = "ghostty --title=btop -e btop" }})
hl.workspace_rule({{ workspace = "special:nmtui",    on_created_empty = "ghostty --title=nmtui -e nmtui" }})
hl.workspace_rule({{ workspace = "special:bluetui",  on_created_empty = "ghostty --title=bluetui -e bluetui" }})
hl.workspace_rule({{ workspace = "special:pavucontrol", on_created_empty = "pavucontrol" }})

-- Window rules for drawers - match by title/class and assign to special workspace
hl.window_rule({{ match = {{ title = "btop" }}, workspace = "special:btop", float = true }})
hl.window_rule({{ match = {{ title = "nmtui" }}, workspace = "special:nmtui", float = true }})
hl.window_rule({{ match = {{ title = "bluetui" }}, workspace = "special:bluetui", float = true }})
hl.window_rule({{ match = {{ class = "org.pulseaudio.pavucontrol" }}, workspace = "special:pavucontrol", float = true }})

-- Size rules
hl.window_rule({{ match = {{ title = "btop" }}, size = {{ {btop_w}, {btop_h} }} }})
hl.window_rule({{ match = {{ title = "nmtui" }}, size = {{ {nm_w}, {nm_h} }} }})
hl.window_rule({{ match = {{ title = "bluetui" }}, size = {{ {bt_w}, {bt_h} }} }})
hl.window_rule({{ match = {{ class = "org.pulseaudio.pavucontrol" }}, size = {{ {pavu_w}, {pavu_h} }} }})
hl.window_rule({{ match = {{ class = "com.system.editor" }}, size = {{ {editor_w}, {editor_h} }} }})

-- Position rules
hl.window_rule({{ match = {{ title = "btop" }}, move = {{ {btop_x}, {bar_y} }} }})
hl.window_rule({{ match = {{ title = "nmtui" }}, move = {{ {nm_x}, {bar_y} }} }})
hl.window_rule({{ match = {{ title = "bluetui" }}, move = {{ {bt_x}, {bar_y} }} }})
hl.window_rule({{ match = {{ class = "org.pulseaudio.pavucontrol" }}, move = {{ {pavu_x}, {bar_y} }} }})
hl.window_rule({{ match = {{ class = "com.system.editor" }}, move = {{ {editor_x}, {editor_y} }} }})
"""
        conf_file = self._env.home_dir / ".config" / "hypr" / "drawers.lua"
        
        needs_write = True
        if conf_file.exists():
            try:
                if conf_file.read_text() == content:
                    needs_write = False
            except Exception:
                pass

        if needs_write:
            if self._exec.dry_run:
                print(f"[DRY-RUN] Would write file {conf_file} with content:\n{content}")
            else:
                conf_file.parent.mkdir(parents=True, exist_ok=True)
                conf_file.write_text(content)
                self._exec.execute(["hyprctl", "reload"])
