#!/bin/bash
# Auto-generates drawers.lua using live monitor data from hyprctl.
# Called from apply.sh (inside a running Hyprland session).

CONF="$HOME/.config/hypr/drawers.lua"

# Read first monitor: pixel dimensions + scale
MON=$(hyprctl monitors -j | jq '.[0]')
PX_W=$(echo "$MON" | jq '.width')
PX_H=$(echo "$MON" | jq '.height')
SCALE=$(echo "$MON" | jq '.scale')

# Logical resolution = pixels / scale
LOG_W=$(awk "BEGIN {printf \"%d\", $PX_W / $SCALE}")

BAR_Y=39   # bar height (36) + bar border (3)

# Drawer sizes - edit these freely
BTOP_W=1400; BTOP_H=600
PAVU_W=800;  PAVU_H=600
NM_W=700;    NM_H=420
BT_W=700;    BT_H=520

# Centered x = (logical_width - drawer_width) / 2
BTOP_X=$(( (LOG_W - BTOP_W) / 2 ))
PAVU_X=$(( (LOG_W - PAVU_W) / 2 ))
NM_X=$(( (LOG_W - NM_W) / 2 ))
BT_X=$(( (LOG_W - BT_W) / 2 ))

cat > "$CONF" << EOF
-- Auto-generated by gen-drawers.sh -- do not edit manually
-- Monitor: \${PX_W}x\${PX_H} @ scale \${SCALE} -> logical \${LOG_W}px wide

-- Special workspaces (drawers) with auto-start commands
hl.workspace_rule({ workspace = "special:btop",     on_created_empty = "ghostty --title=btop -e btop" })
hl.workspace_rule({ workspace = "special:nmtui",    on_created_empty = "ghostty --title=nmtui -e nmtui" })
hl.workspace_rule({ workspace = "special:bluetui",  on_created_empty = "ghostty --title=bluetui -e bluetui" })
hl.workspace_rule({ workspace = "special:pavucontrol", on_created_empty = "pavucontrol" })

-- Window rules for drawers - match by title/class and assign to special workspace
hl.window_rule({ match = { title = "btop" }, workspace = "special:btop", float = true })
hl.window_rule({ match = { title = "nmtui" }, workspace = "special:nmtui", float = true })
hl.window_rule({ match = { title = "bluetui" }, workspace = "special:bluetui", float = true })
hl.window_rule({ match = { class = "org.pulseaudio.pavucontrol" }, workspace = "special:pavucontrol", float = true })

-- Size rules
hl.window_rule({ match = { title = "btop" }, size = { $BTOP_W, $BTOP_H } })
hl.window_rule({ match = { title = "nmtui" }, size = { $NM_W, $NM_H } })
hl.window_rule({ match = { title = "bluetui" }, size = { $BT_W, $BT_H } })
hl.window_rule({ match = { class = "org.pulseaudio.pavucontrol" }, size = { $PAVU_W, $PAVU_H } })

-- Position rules
hl.window_rule({ match = { title = "btop" }, move = { $BTOP_X, $BAR_Y } })
hl.window_rule({ match = { title = "nmtui" }, move = { $NM_X, $BAR_Y } })
hl.window_rule({ match = { title = "bluetui" }, move = { $BT_X, $BAR_Y } })
hl.window_rule({ match = { class = "org.pulseaudio.pavucontrol" }, move = { $PAVU_X, $BAR_Y } })
EOF

echo "Generated \$CONF (logical \${LOG_W}px wide @ scale \${SCALE})"