#!/bin/bash
# Auto-generates drawers.conf using live monitor data from hyprctl.
# Called from apply.sh (inside a running Hyprland session).

CONF="$HOME/.config/hypr/drawers.conf"

# Read first monitor: pixel dimensions + scale
MON=$(hyprctl monitors -j | jq '.[0]')
PX_W=$(echo "$MON" | jq '.width')
PX_H=$(echo "$MON" | jq '.height')
SCALE=$(echo "$MON" | jq '.scale')

# Logical resolution = pixels / scale
LOG_W=$(awk "BEGIN {printf \"%d\", $PX_W / $SCALE}")

BAR_Y=39   # bar height (36) + bar border (3)

# Drawer sizes — edit these freely
BTOP_W=1400; BTOP_H=600
PAVU_W=800;  PAVU_H=600
NM_W=700;    NM_H=420
BT_W=700;    BT_H=520

# Centered x = (logical_width - drawer_width) / 2
BTOP_X=$(( (LOG_W - BTOP_W) / 2 ))
PAVU_X=$(( (LOG_W - PAVU_W) / 2 ))
NM_X=$(( (LOG_W - NM_W) / 2 ))
BT_X=$(( (LOG_W - BT_W) / 2 ))

cat > "$CONF" << EOF
# Auto-generated by gen-drawers.sh — do not edit manually
# Monitor: ${PX_W}x${PX_H} @ scale ${SCALE} → logical ${LOG_W}px wide
#
workspace = special:btop,     on-created-empty:ghostty --title=btop -e btop
workspace = special:nmtui,    on-created-empty:ghostty --title=nmtui -e nmtui
workspace = special:bluetui,  on-created-empty:ghostty --title=bluetui -e bluetui
workspace = special:pavucontrol,  on-created-empty:pavucontrol

windowrule = float on,             match:title btop
windowrule = float on,             match:title nmtui
windowrule = float on,             match:title bluetui
windowrule = float on,             match:class org.pulseaudio.pavucontrol

windowrule = size $BTOP_W $BTOP_H, match:title btop
windowrule = size $NM_W   $NM_H,   match:title nmtui
windowrule = size $BT_W   $BT_H,   match:title bluetui
windowrule = size $PAVU_W $PAVU_H, match:class org.pulseaudio.pavucontrol

windowrule = move $BTOP_X $BAR_Y,  match:title btop
windowrule = move $NM_X   $BAR_Y,  match:title nmtui
windowrule = move $BT_X   $BAR_Y,  match:title bluetui
windowrule = move $PAVU_X $BAR_Y,  match:class org.pulseaudio.pavucontrol

EOF

echo "Generated $CONF (logical ${LOG_W}px wide @ scale ${SCALE})"
