-- Auto-generated by gen-drawers.sh -- do not edit manually
-- Monitor: ${PX_W}x${PX_H} @ scale ${SCALE} -> logical ${LOG_W}px wide

-- Special workspaces (drawers) with auto-start commands
hl.workspace_rule({ workspace = "special:btop",     on_created_empty = "ghostty --title=btop -e btop" })
hl.workspace_rule({ workspace = "special:nmtui",    on_created_empty = "ghostty --title=nmtui -e nmtui" })
hl.workspace_rule({ workspace = "special:bluetui",  on_created_empty = "ghostty --title=bluetui -e bluetui" })
hl.workspace_rule({ workspace = "special:pavucontrol", on_created_empty = "pavucontrol" })

-- Window rules for drawers - match by title/class and assign to special workspace
hl.window_rule({ match = { title = "btop" }, workspace = "special:btop", float = true })
hl.window_rule({ match = { title = "nmtui" }, workspace = "special:nmtui", float = true })
hl.window_rule({ match = { title = "bluetui" }, workspace = "special:bluetui", float = true })
hl.window_rule({ match = { class = "org.pulseaudio.pavucontrol" }, workspace = "special:pavucontrol", float = true })

-- Size rules
hl.window_rule({ match = { title = "btop" }, size = { 1400, 600 } })
hl.window_rule({ match = { title = "nmtui" }, size = { 700, 420 } })
hl.window_rule({ match = { title = "bluetui" }, size = { 700, 520 } })
hl.window_rule({ match = { class = "org.pulseaudio.pavucontrol" }, size = { 800, 600 } })
hl.window_rule({ match = { class = "com.system.editor" }, size = { 700, 600 } })

-- Position rules
hl.window_rule({ match = { title = "btop" }, move = { 100, 39 } })
hl.window_rule({ match = { title = "nmtui" }, move = { 450, 39 } })
hl.window_rule({ match = { title = "bluetui" }, move = { 450, 39 } })
hl.window_rule({ match = { class = "org.pulseaudio.pavucontrol" }, move = { 400, 39 } })
hl.window_rule({ match = { class = "com.system.editor" }, move = { 890, 150 } })
