-- Hyprland Lua Configuration
-- Migrated from hyprlang config

-- Load configuration modules
require("look_and_feel")
require("monitor")
require("input")
require("keybinds")
require("windowrules")
require("autostart")

-- Load drawers if generated (auto-generated by gen-drawers.sh on startup)
local drawers_path = os.getenv("HOME") .. "/.config/hypr/drawers.lua"
local f = io.open(drawers_path, "r")
if f then
    f:close()
    require("drawers")
end

-- Remove autogenerated warning if present
hl.config({ autogenerated = false })