# Override OPTIONS to disable debug package generation.
# This prevents warnings like 'gdb-add-index: No index was created' on pre-compiled packages (e.g. electron-bin)
# and significantly speeds up AUR package builds by avoiding unnecessary debug symbol extraction.
OPTIONS=(strip docs !libtool !staticlibs emptydirs zipman purge !debug lto)
