import re
from pathlib import Path
from dotfiles_api.domain.tokens import DesignTokens
from dotfiles_api.domain.artifacts import GeneratedArtifact
from dotfiles_api.infrastructure.generators.base import BaseGenerator
from dotfiles_api.application.transaction import ConfigTransaction
from dotfiles_api.domain.events import EventBus

class BtopGenerator(BaseGenerator):
    def __init__(self, name: str = "btop", transaction: ConfigTransaction = None, event_bus: EventBus = None) -> None:
        super().__init__(name, transaction, event_bus)

    def render(self, tokens: DesignTokens, theme_name: str) -> list[GeneratedArtifact]:
        bg = tokens.colors.colors.get("background", "#F4EFE4")
        bg2 = tokens.colors.colors.get("background2", "#EDE7D3")
        fg = tokens.colors.colors.get("foreground", "#0D0D0D")
        fg2 = tokens.colors.colors.get("foreground2", "#3A3A3A")
        border = tokens.colors.colors.get("border", "#0D0D0D")
        accent = tokens.colors.colors.get("accent", "#D94F2B")
        inactive = tokens.colors.colors.get("inactive", "#C8C2B4")

        theme_content = f"""# btop theme auto-generated by BtopGenerator
# Theme: {theme_name}

# Main UI elements
theme[main_bg]="{bg}"
theme[main_fg]="{fg}"
theme[title]="{accent}"
theme[hi_fg]="{accent}"
theme[selected_bg]="{bg2}"
theme[selected_fg]="{fg}"
theme[inactive_fg]="{inactive}"
theme[graph_text]="{fg2}"

# Box outlines
theme[cpu_box]="{border}"
theme[mem_box]="{border}"
theme[net_box]="{border}"
theme[proc_box]="{border}"
theme[div_line]="{border}"

# Temp colors
theme[temp_start]="{inactive}"
theme[temp_mid]="{accent}"
theme[temp_end]="{accent}"

# CPU graph / meter
theme[cpu_start]="{inactive}"
theme[cpu_mid]="{accent}"
theme[cpu_end]="{accent}"

# Memory
theme[free_start]="{inactive}"
theme[free_mid]="{accent}"
theme[free_end]="{accent}"
theme[cached_start]="{inactive}"
theme[cached_mid]="{accent}"
theme[cached_end]="{accent}"
theme[available_start]="{inactive}"
theme[available_mid]="{accent}"
theme[available_end]="{accent}"
theme[used_start]="{inactive}"
theme[used_mid]="{accent}"
theme[used_end]="{accent}"

# Download / Upload
theme[download_start]="{inactive}"
theme[download_mid]="{accent}"
theme[download_end]="{accent}"
theme[upload_start]="{inactive}"
theme[upload_mid]="{accent}"
theme[upload_end]="{accent}"

# Process meter
theme[process_start]="{inactive}"
theme[process_mid]="{accent}"
theme[process_end]="{accent}"
"""
        config_content = 'color_theme = "shade-raid"\n'
        if self.transaction and self.transaction._env:
            conf_path = self.transaction._env.home_dir / ".config" / "btop" / "btop.conf"
            if conf_path.exists():
                try:
                    orig = conf_path.read_text()
                    config_content = re.sub(r'^color_theme\s*=.*', 'color_theme = "shade-raid"', orig, flags=re.MULTILINE)
                except Exception:
                    pass

        return [
            GeneratedArtifact(artifact_id="btop-theme", content=theme_content),
            GeneratedArtifact(artifact_id="btop-config", content=config_content)
        ]
