[search]
placeholder = "/ search"

[ui]
width = 700
max_entries = 8
icons = true

[[modules]]
name = "applications"
placeholder = "apps"

[[modules]]
name = "runner"
placeholder = "run"

[[modules]]
name = "clipboard"
placeholder = "clipboard"

[[modules]]
name = "emojis"
placeholder = "emoji"

[[modules]]
name = "calc"
placeholder = "calc"
