from dotfiles_api.infrastructure.capabilities.walker import WalkerLauncher
from dotfiles_api.infrastructure.capabilities.waybar import WaybarStatusBar
from dotfiles_api.infrastructure.capabilities.swaync import SwayNCNotificationCenter
from dotfiles_api.infrastructure.capabilities.hyprland import HyprlandCompositor
